trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@1
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js 22'

- script: |
    npm install
    npm run build      # Remove this line if you don't have a build step
    npm test
  displayName: 'Install dependencies, build, and run tests'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive application files'

- upload: '$(Build.ArtifactStagingDirectory)/app.zip'
  artifact: drop

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<your-azure-service-connection>'
    appType: 'webApp'
    appName: '<your-app-service-name>'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Deploy to Azure Web App'
